[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "librosa>=0.11.0",
    "soundfile>=0.13.1",
    "spleeter>=2.4.2",
    "tensorflow>=2.12.1",
]
